# Generated by Django 4.2 on 2023-05-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id_tipoPedido', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('fk_Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cliente_Usuario.usuario')),
                ('Sueldo', models.FloatField()),
            ],
            bases=('Cliente_Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cliente_Usuario.usuario')),
                ('Observaciones', models.CharField(max_length=50)),
            ],
            bases=('Cliente_Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Alcance', models.CharField(max_length=50)),
                ('Plazo_inicio', models.DateField()),
                ('Plazo_fin', models.DateField()),
                ('Presupuesto', models.FloatField()),
                ('Info_adicional', models.CharField(max_length=50)),
                ('fk_Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.estado')),
                ('fk_TipoPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.tipopedido')),
                ('fk_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cliente_Usuario.usuario')),
                ('Sueldo', models.FloatField()),
                ('fk_Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.administrador')),
            ],
            bases=('Cliente_Usuario.usuario',),
        ),
        migrations.CreateModel(
            name='PedidoTrabajador',
            fields=[
                ('id_pedidoTrabajador', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.pedido')),
                ('fk_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.trabajador')),
            ],
        ),
    ]
