# Generated by Django 4.2 on 2023-05-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('Sueldo', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('Observaciones', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Alcance', models.CharField(max_length=50)),
                ('Plazo_inicio', models.DateField()),
                ('Plazo_fin', models.DateField()),
                ('Presupuesto', models.FloatField()),
                ('Info_adicional', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('fk_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.cliente')),
                ('fk_Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id_tipoPedido', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('Sueldo', models.FloatField()),
                ('Fecha_Ingreso', models.DateField(null=True)),
                ('Especialidad', models.CharField(max_length=50, null=True)),
                ('fk_Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.administrador')),
                ('fk_Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoTrabajador',
            fields=[
                ('id_pedidoTrabajador', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Aceptado', models.DateField(null=True)),
                ('fk_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.pedido')),
                ('fk_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_TipoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.tipopedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_Rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.rol'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='fk_Rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.rol'),
        ),
    ]
