# Generated by Django 4.2 on 2023-05-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Status',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Observaciones',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipopedido',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.status'),
        ),
    ]
