# Generated by Django 4.2 on 2023-05-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0002_status_remove_pedido_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fk_Estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
