# Generated by Django 4.2 on 2023-05-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0005_alter_administrador_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.cliente'),
        ),
    ]
