# Generated by Django 4.2 on 2023-05-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0011_alter_administrador_fk_rol_alter_cliente_fk_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fk_Administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente_Usuario.administrador'),
        ),
    ]
