# Generated by Django 4.2 on 2023-06-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0012_alter_trabajador_fk_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='Sueldo',
            field=models.FloatField(null=True),
        ),
    ]
