# Generated by Django 4.2 on 2023-06-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0013_alter_trabajador_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='Sueldo',
            field=models.FloatField(null=True),
        ),
    ]
