# Generated by Django 4.2 on 2023-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_Usuario', '0014_alter_administrador_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Observaciones',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Alcance',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Info_adicional',
            field=models.CharField(max_length=500),
        ),
    ]
