# Generated by Django 4.2 on 2023-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canonical', models.CharField(verbose_name='Canonical')),
                ('RowKey', models.DateTimeField(verbose_name='RowKey')),
                ('INF_Label', models.CharField(max_length=100, verbose_name='INF_Label')),
                ('INF_Value', models.FloatField(verbose_name='INF_Value')),
                ('STA_Label', models.CharField(max_length=100, verbose_name='STA_Label')),
                ('Sector_Neta', models.CharField(max_length=100, verbose_name='Sector_Neta')),
            ],
        ),
    ]
