# Generated by Django 4.2 on 2023-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='temp')),
                ('visibility', models.FloatField(verbose_name='visibility')),
                ('datetimeStr', models.DateTimeField(verbose_name='datetimeStr')),
            ],
        ),
    ]
